### ISSUE TITLE
No response in a timely manner on Opera 11.51

### ISSUE THREAD

**Issue by imk** [operasoftware/operaprestodriver#17]
When trying to launch Opera WebDriver from Java (Version 0.7 from maven repository) with one of the following codes:

``` java
DesiredCapabilities operaCapabilities = DesiredCapabilities.opera();
WebDriver driver = new OperaDriver(operaCapabilities);
```

or after starting explizit Selenium Hub and a webdriver instance like this:

```
java -jar selenium-2.5.0/selenium-server-standalone-2.5.0.jar -role hub
```

and

```
java -jar selenium-2.5.0/selenium-server-standalone-2.5.0.jar -role webdriver -hub http://localhost:4444/grid/register -port 5556 -browser browserName=opera,version=11.51
```

``` java
DesiredCapabilities operaCapabilities = DesiredCapabilities.opera();
WebDriver driver = new OperaDriver(operaCapabilities);
```

i'm allways just seeing an opera window with "connecting to debugger" (opera:debug), when clicking to connect, nothing happens, clicking a second time brings a "connection failed" message. Maybe I'm missing something on how to use opera webdriver, but couldn't find any hint ...

System:
- OperaDriver 0.7
- Opera 11.51
- Ubuntu 11.04 64-bit

PS: When setting

```
operaCapabilities.setCapability("opera.autostart", false);
```

and manually connecting to WebDriver is working - but hard to automate it ;o)

**Comment by Stuk** [comment]
Hmm, strange, that shouldn't happen. However first of all I think you should be doing:

```
WebDriver driver = new RemoteWebDriver(new URL("http://127.0.0.1:4444/wd/hub"), operaCapabilities);
```

to start the driver on the hub. See if that works :)

**Comment by imk** [comment]
Oh sorry, copy and paste error on creating the issue: After starting selenium server (with explicit opera browser config on command line as described in first comment), I tried with RemoteWebDriver like in your example:

``` java
DesiredCapabilities operaCapabilities = DesiredCapabilities.opera();
WebDriver driver = new RemoteWebDriver(new URL("http://127.0.0.1:4444/wd/hub"), operaCapabilities);
```

Same behaviour: opera is launched and waitingin with the "connecting to debugger" window, after some time, I get a exception and opera is closed, this is the exception on the java console in eclipse:

```
Exception in thread "main" org.openqa.selenium.WebDriverException: No response in a timely fashion.
Build info: version: '2.5.0', revision: '13516', time: '2011-08-23 18:29:57'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.38-11-generic', java.version: '1.6.0_26'
Driver info: driver.version: OperaDriver
Build info: version: '2.5.0', revision: '13548', time: '2011-08-24 13:44:31'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.38-11-generic', java.version: '1.6.0_26'
Driver info: driver.version: RemoteWebDriver
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:131)
    at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:105)
    at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:405)
    at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:104)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:87)
    at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:95)
    at com.martinkurz.tests.SeleniumTest.main(SeleniumTest.java:43)
Caused by: com.opera.core.systems.scope.exceptions.ResponseNotReceivedException: No response in a timely fashion.
Build info: version: '2.5.0', revision: '13516', time: '2011-08-23 18:29:57'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.38-11-generic', java.version: '1.6.0_26'
Driver info: driver.version: OperaDriver
Build info: version: '2.5.0', revision: '13548', time: '2011-08-24 13:44:31'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.38-11-generic', java.version: '1.6.0_26'
Driver info: driver.version: OperaDriver
    at com.opera.core.systems.WaitState.pollResultItem(WaitState.java:414)
    at com.opera.core.systems.WaitState.waitAndParseResult(WaitState.java:424)
    at com.opera.core.systems.WaitState.waitForHandshake(WaitState.java:605)
    at com.opera.core.systems.ScopeServices.waitForHandshake(ScopeServices.java:283)
    at com.opera.core.systems.ScopeServices.init(ScopeServices.java:206)
    at com.opera.core.systems.OperaDriver.init(OperaDriver.java:205)
    at com.opera.core.systems.OperaDriver.<init>(OperaDriver.java:151)
    at com.opera.core.systems.OperaDriver.<init>(OperaDriver.java:103)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at java.lang.Class.newInstance0(Class.java:355)
    at java.lang.Class.newInstance(Class.java:308)
    at org.openqa.selenium.remote.server.DefaultDriverFactory.callConstructor(DefaultDriverFactory.java:90)
    at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:81)
    at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:154)
    at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
```

and this is the selenium servers log:

```
19:36:14.992 ERROR - Error initializing OperaDriver with exception 
com.opera.core.systems.scope.exceptions.ResponseNotReceivedException: No response in a timely fashion.
Build info: version: '2.5.0', revision: '13516', time: '2011-08-23 18:29:57'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.38-11-generic', java.version: '1.6.0_26'
Driver info: driver.version: OperaDriver
    at com.opera.core.systems.WaitState.pollResultItem(WaitState.java:414)
    at com.opera.core.systems.WaitState.waitAndParseResult(WaitState.java:424)
    at com.opera.core.systems.WaitState.waitForHandshake(WaitState.java:605)
    at com.opera.core.systems.ScopeServices.waitForHandshake(ScopeServices.java:283)
    at com.opera.core.systems.ScopeServices.init(ScopeServices.java:206)
    at com.opera.core.systems.OperaDriver.init(OperaDriver.java:205)
    at com.opera.core.systems.OperaDriver.<init>(OperaDriver.java:151)
    at com.opera.core.systems.OperaDriver.<init>(OperaDriver.java:103)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at java.lang.Class.newInstance0(Class.java:355)
    at java.lang.Class.newInstance(Class.java:308)
    at org.openqa.selenium.remote.server.DefaultDriverFactory.callConstructor(DefaultDriverFactory.java:90)
    at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:81)
    at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:154)
    at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
19:36:14.993 INFO - Caught exception when trying to shut down : null
19:36:15.486 INFO - Executing: org.openqa.selenium.remote.server.handler.Status@495c998a at URL: /status)
19:36:15.486 INFO - Done: /status
19:36:15.982 WARN - Exception thrown
java.util.concurrent.ExecutionException: org.openqa.selenium.WebDriverException: com.opera.core.systems.scope.exceptions.ResponseNotReceivedException: No response in a timely fashion.
Build info: version: '2.5.0', revision: '13516', time: '2011-08-23 18:29:57'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.38-11-generic', java.version: '1.6.0_26'
Driver info: driver.version: OperaDriver
Build info: version: '2.5.0', revision: '13516', time: '2011-08-23 18:29:57'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.38-11-generic', java.version: '1.6.0_26'
Driver info: driver.version: OperaDriver
    at java.util.concurrent.FutureTask$Sync.innerGet(FutureTask.java:222)
    at java.util.concurrent.FutureTask.get(FutureTask.java:83)
    at org.openqa.selenium.remote.server.DefaultSession.execute(DefaultSession.java:116)
    at org.openqa.selenium.remote.server.DefaultSession.<init>(DefaultSession.java:87)
    at org.openqa.selenium.remote.server.DefaultSession.createSession(DefaultSession.java:73)
    at org.openqa.selenium.remote.server.DefaultDriverSessions.newSession(DefaultDriverSessions.java:87)
    at org.openqa.selenium.remote.server.handler.NewSession.handle(NewSession.java:47)
    at org.openqa.selenium.remote.server.rest.ResultConfig.handle(ResultConfig.java:153)
    at org.openqa.selenium.remote.server.DriverServlet.handleRequest(DriverServlet.java:389)
    at org.openqa.selenium.remote.server.DriverServlet.doPost(DriverServlet.java:371)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.openqa.jetty.jetty.servlet.ServletHolder.handle(ServletHolder.java:428)
    at org.openqa.jetty.jetty.servlet.ServletHandler.dispatch(ServletHandler.java:677)
    at org.openqa.jetty.jetty.servlet.ServletHandler.handle(ServletHandler.java:568)
    at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1530)
    at org.openqa.jetty.http.HttpContext.handle(HttpContext.java:1482)
    at org.openqa.jetty.http.HttpServer.service(HttpServer.java:909)
    at org.openqa.jetty.http.HttpConnection.service(HttpConnection.java:820)
    at org.openqa.jetty.http.HttpConnection.handleNext(HttpConnection.java:986)
    at org.openqa.jetty.http.HttpConnection.handle(HttpConnection.java:837)
    at org.openqa.jetty.http.SocketListener.handleConnection(SocketListener.java:243)
    at org.openqa.jetty.util.ThreadedServer.handle(ThreadedServer.java:357)
    at org.openqa.jetty.util.ThreadPool$PoolThread.run(ThreadPool.java:534)
Caused by: org.openqa.selenium.WebDriverException: com.opera.core.systems.scope.exceptions.ResponseNotReceivedException: No response in a timely fashion.
Build info: version: '2.5.0', revision: '13516', time: '2011-08-23 18:29:57'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.38-11-generic', java.version: '1.6.0_26'
Driver info: driver.version: OperaDriver
Build info: version: '2.5.0', revision: '13516', time: '2011-08-23 18:29:57'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.38-11-generic', java.version: '1.6.0_26'
Driver info: driver.version: OperaDriver
    at com.opera.core.systems.OperaDriver.<init>(OperaDriver.java:157)
    at com.opera.core.systems.OperaDriver.<init>(OperaDriver.java:103)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at java.lang.Class.newInstance0(Class.java:355)
    at java.lang.Class.newInstance(Class.java:308)
    at org.openqa.selenium.remote.server.DefaultDriverFactory.callConstructor(DefaultDriverFactory.java:90)
    at org.openqa.selenium.remote.server.DefaultDriverFactory.newInstance(DefaultDriverFactory.java:81)
    at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:154)
    at org.openqa.selenium.remote.server.DefaultSession$BrowserCreator.call(DefaultSession.java:1)
    at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
    at java.util.concurrent.FutureTask.run(FutureTask.java:138)
    at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
    at java.lang.Thread.run(Thread.java:662)
Caused by: com.opera.core.systems.scope.exceptions.ResponseNotReceivedException: No response in a timely fashion.
Build info: version: '2.5.0', revision: '13516', time: '2011-08-23 18:29:57'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.38-11-generic', java.version: '1.6.0_26'
Driver info: driver.version: OperaDriver
    at com.opera.core.systems.WaitState.pollResultItem(WaitState.java:414)
    at com.opera.core.systems.WaitState.waitAndParseResult(WaitState.java:424)
    at com.opera.core.systems.WaitState.waitForHandshake(WaitState.java:605)
    at com.opera.core.systems.ScopeServices.waitForHandshake(ScopeServices.java:283)
    at com.opera.core.systems.ScopeServices.init(ScopeServices.java:206)
    at com.opera.core.systems.OperaDriver.init(OperaDriver.java:205)
    at com.opera.core.systems.OperaDriver.<init>(OperaDriver.java:151)
    ... 16 more
19:36:16.027 WARN - Exception: No response in a timely fashion.
Build info: version: '2.5.0', revision: '13516', time: '2011-08-23 18:29:57'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '2.6.38-11-generic', java.version: '1.6.0_26'
Driver info: driver.version: OperaDriver
```

PS: When starting the opera hub on a windows xp vm, the RemotwWebDriver is working. So it's either a problem with x86_64 launcher or x86_64 opera

**Comment by Stuk** [comment]
It looks like the `-autotestmode` flag isn't getting passed to Opera. Could you tell me what your `opera` command looks like? (It's actually a script file, can be seen with

```
more `which opera`
```

**Comment by imk** [comment]
no problem, here it is:

```
~$ more `which opera`
#!/bin/sh
export OPERA_DIR=${OPERA_DIR:-/usr/share/opera}
exec /usr/lib/opera/opera "$@"
```

when using OperaDriver (because it's faster to test and shows the same behaviour as RemoteWebDriver), I can see the following processes running:

```
/home/martink/.launcher/launcher-linux-x86_64 -host 127.0.0.1 -port 12559 -bin /usr/bin/opera -autotestmode
/usr/lib/opera/opera -autotestmode
```

**Comment by asmorodskiy** [comment]
Confirm same behavior for selenium version 2.6 . And selenium server running on WIndows XP SP3 . Feel free to request any additional details .

**Comment by andreastt** [comment]
I doubt this is a problem with the RemoteWebDriver or the Selenium server at all.  Can you try to delete your autotestmode profile directory?  On GNU/Linux it's located in ~/.autotestmode, on Windows in C:\Program Files\Opera\ somewhere.

By the way, you shouldn't have to click Connect on the opera:debug page you see when Opera starts.  When Opera is started with the -autotestmode command-line argument, Proxy Auto Connect should get enabled by default.  Can you start Opera manually with -autotestmode, go to opera:config and check whether the Proxy Auto Connect setting is getting enabled also?

**Comment by asmorodskiy** [comment]
1. Couldn't find .autotestmode  in Windows
2. I realised in my case problem appear only starting from second test and actual cause of my issue is that first test can't correctly close opera instance . I found that first test finishes with such warning :

<code>
06:43:26.325 WARN - Got ERROR for 31
</code>

So all other tests fails because they get not correctly closed opera instance .

Suspecting that actually my issue not related to this certain defect. What do you think ?

**Comment by imk** [comment]
Yes, it's working! I deleted directory `~/.opera-autotest` (there was no `~/.autotestmode`) and opera 11.51 is directly switching from "Connecting ..." Window to the pages called from test case. (also updated to selenium-java 2.6 and operadriver 0.7.3)

To me, this issue is fixed now, @asmorodskiy: Sounds like a different problem to me, so it should be created a new issue for this behaviour.

**Comment by mourasman** [comment]
I'm still having this issue with 0.7 version and even after deleting "profile-autotest" folder...  The browser window opens, the page is loaded, but it freezes right after... I'm trying to start it through Grid, btw, which I think should be irrelevant... Does anyone know anything about this?

Best regards,
Mourasman

**Comment by andreastt** [comment]
Does it happen when you run OperaDriver locally as well?  Can you link to the page?  Is the page itself JavaScript-heavy?

**Comment by mourasman** [comment]
It happens even when i run it locally and the page is this one:
https://demoisq.csod.com

It's a bit JS heavy indeed, but it's not a monstrosity, i guess :)

2011/10/20 Andreas Tolf Tolfsen <
reply@reply.github.com>

**Comment by imk** [comment]
Did you try version 0.7.3 too or version 0.7? I also updated to the latest versions of operadriver and selenium before deleting the folder.

**Comment by mourasman** [comment]
It is the 0.7.3, I started using Opera driver today :p

2011/10/20 Martin Kurz <
reply@reply.github.com>

**Comment by mourasman** [comment]
I also noticed that the driver is veeeeery slow when loading pages and very unresponsive...
