### ISSUE TITLE
Exceptions on handling page loads: No response in a timely fashion

### ISSUE THREAD

**Issue by lkende** [operasoftware/operaprestodriver#71]
I see this topic in both the open and closed issues, but decided to open a new one as it's time for me to really delve into this issue.  It would be greatly appreciated if we can work closely to resolve this and apparently would also be helpful to many others, in addition to getting OperaDriver up to par as a solid automation testing tool.

I have multiple URLs/pages (meaning 1000s) that throw exceptions or cause Opera to crash and close with OperaDriver.  These same pages work fine with the other browser's WebDrivers.  In fact these same URLs load fine in Opera when run normally.  This has been an ongoing issue but have not had time focus in on it until now. I believe this is the same issue that others are referring to related to long page loads or heavy javascript functions on document ready. 

Before I dump a lot of information, like log data, URLs that fail, browser/selenium/platform versions, I want to ask if you guys have a sense that there's a problem here?  That there is something failing with the way OperaDriver launches with an autotest profile, loads a given page, determines that the document is loaded and ready, and then returns control to the initialized driver.

(A little background: I built and manage the screenshot system for a web service that runs on selenium webdriver.  We offer screenshots across multiple OS/Browser combos and run 1000s a day.  I have spent a lot of time getting OperaDriver working to the point that it is, and of all the requests, Opera fails the most  and usually fails in the startup and page load process. Here's a copy of my log of the top five failures for today:)

Windows 7/Opera 11.5, failed 124, good 50
Windows 7/Internet Explorer 8, failed 24, good 73
Windows XP SP2/Internet Explorer 7, failed 23, good 153
Windows Vista/Internet Explorer 7, failed 20, good 72
Windows XP SP2/Internet Explorer 6, failed 18, good 113

Currently we are in the process of upgrading our 11.5's to 11.62 (the latest as of the time this is being written) across all of our virtual instances.  On my local machine I have been testing with the latest and am still seeing the issue.  Here's my specs:

Window 7 64-bit
Opera 11.62
Selenium 2.20

Here's a recent URL of a customer that fails: http://martinpresse.com/

Here are a couple of reasons (I am guessing at the moment) for why I think OperaDriver fails to load a URL:
- there is an element that isn't loading quick enough (I see 20/21 in the address bar most of the time, where one element isn't finishing the load)
- javascript loads more elements on DOM ready.
- visually I see cases where Opera loads the html but the images don't show up - in the URL mentioned above, the page has one image file that was not found... could that be a cause? 
- external resources to google analytics or maps

Let me know your thoughts or if I can provide more information.

Thanks,
Luke

**Comment by andreastt** [comment]
Hi Luke, thanks for looking into this.

To be able to debug this I need concrete examples of what kind of exceptions are getting thrown, and if possible, a reproducible test case.

Running

```
driver.get("http://martinpresse.com/")
```

on latest HEAD does not cause any problems for me on OS X 10.7.

We used to have an issue of OperaDriver not returning control to the user when timing out on a get() or click() command.  This should be addressed with 0.11 and above.

Is this a persistent issue for you still?

**Comment by lkende** [comment]
Thanks. Yes, the issue is still persistent.  I should will soon be able to put my attention back to this to give you some more info.

Is there a reference where one can see the relationship between OperaDriver version and selenium version?  I test with many selenium versions as there are varying degrees of browser support and bug workarounds.

**Comment by andreastt** [comment]
You can see which version of OperaDriver related to which Selenium version in the https://github.com/operasoftware/operadriver/blob/master/CHANGES file.

**Comment by lkende** [comment]
Since upgrading to the latest version of selenium 2.25, which I believe uses v 0.18 of OperaDriver, and only running Opera 11.52 or higher, I am not seeing this issue anymore.  Not sure what has changed, but glad to see OperaDriver working reliably!  Good job guys!
